Feature/export books
DroiDevs-PL/books pull request #7
Opened 2017-12-27 18:35 UTC by nani92

2018-01-03 22:22 UTC, klisiewicz requested changes
A lot of good work, but some code requires changes.

2018-01-03 22:22 UTC, klisiewicz commented on app/src/main/java/pl/droidevs/books/library/CSVHelper.java
> +public class CSVHelper {
Ta klasa chyba nie musi być publiczna?

2018-01-03 22:22 UTC, klisiewicz commented on app/src/main/java/pl/droidevs/books/library/CSVHelper.java
> +        Class bookEntityClass = BookEntity.class;
Po co przechowujesz referencję do obiektu class? Równie dobrze możesz przecież napisać: BookEntity.class.getDeclaredFields()

2018-01-03 22:22 UTC, klisiewicz commented on app/src/main/java/pl/droidevs/books/library/CSVHelper.java
> +        String[] fieldNames = new String[fields.length - 1];
Czemu ilość nazw pól jest o 1 mniejsza niż liczba pól? Jakieś pole jest pomijane?

2018-01-03 22:22 UTC, klisiewicz commented on app/src/main/java/pl/droidevs/books/library/ExportImportViewModel.java
> +public class ExportImportViewModel extends ViewModel {
Pomyślałbym nad lepszą nazwę. Może coś w stylu BookTransferViewModel? Jeśli nie wpadniesz na nic to może zostać ExportImport.

2018-01-03 22:22 UTC, klisiewicz commented on app/src/main/java/pl/droidevs/books/library/ExportImportViewModel.java
> +    public boolean exportBooks() {
Zwracanie flagi jako informację o błędzie nie jest najlepszą parktyką. Co mówi mi wywołanie if (exportBooks())? Czy true oznacza, że są książki do eskportu? Czy że można eksportować książki? A może, że udało się wyeksportować? Nie mogę jednoznacznie odpowiedzieć na to pytanie bez zaglądania do kodu tej metody.

2018-01-03 22:22 UTC, klisiewicz commented on app/src/main/java/pl/droidevs/books/library/ExportImportViewModel.java
> +        final boolean[] wasSavingSuccessful = {true};
Często jedna zła decyzja prowadzi do kolejnej - hack do zmieniania wartości wewnątrz klasy anonimowej 😉

2018-01-03 22:22 UTC, klisiewicz commented on app/src/main/java/pl/droidevs/books/library/ExportImportViewModel.java
> +                    wasSavingSuccessful[0] = false;
A można by tutaj stworzyć dedykowany wyjątek w stylu ExportFailedException i owrapować nim IOException i wyrzucić do klienta.

2018-01-03 22:22 UTC, klisiewicz commented on app/src/main/java/pl/droidevs/books/library/ExportImportViewModel.java
> +    private File getFile() throws IOException {
Ta metoda tak naprawdę tworzy plik, a nie tylko go zwraca.

2018-01-03 22:22 UTC, klisiewicz commented on app/src/main/java/pl/droidevs/books/library/ExportImportViewModel.java
> +        if (!file.exists()) {
Moim skromnym zdaniem warunki bez negacji czyta się łatwiej 😉 Ale to tylko sugestia.

2018-01-03 22:22 UTC, klisiewicz commented on app/src/main/java/pl/droidevs/books/library/LibraryActivity.java
> +        if (hasPermission(Manifest.permission.WRITE_EXTERNAL_STORAGE)) {
Może stworzyć metodę canWriteStorage()? Albo hasWriteStoragePermission?

2018-01-03 22:22 UTC, klisiewicz commented on app/src/main/java/pl/droidevs/books/library/LibraryActivity.java
> +            requestPermissions(Manifest.permission.WRITE_EXTERNAL_STORAGE, REQUEST_PERMISSION_SAVE_FILE_CODE);
Analgoicznie tutaj: requestWriteStoragePermission?

2018-01-04 18:09 UTC, nani92 commented on app/src/main/java/pl/droidevs/books/library/CSVHelper.java
> +        String[] fieldNames = new String[fields.length - 1];
TABLE_NAME

2018-01-04 19:32 UTC, klisiewicz approved these changes
Jedna uwaga, można to zmienić przy najbliższej okazji 👍

2018-01-04 19:32 UTC, klisiewicz commented on app/src/main/java/pl/droidevs/books/exportimport/ExportImportViewModel.java
> +                    throw new ExportFailedException(e.getCause());
Używając `e.getCause()` tracisz prawdziwe źródło wyjątku. Spróbuj uruchomić poniższy test:
`@Test
    public void test() {
        try {
            Scanner in = new Scanner(new FileReader("filename.txt"));
        } catch (IOException e) {
            try {
                throw new ExportFailedException(e.getCause());
            } catch (ExportFailedException ef) {
                ef.printStackTrace();
            }
        }
    }`
Gdy użyjesz `ExportFailedException(e.getCause())` Twój stacktrace będzie wyglądał tak:

> pl.droidevs.books.ExampleUnitTest$ExportFailedException
	at pl.droidevs.books.ExampleUnitTest.test(ExampleUnitTest.java:29)

Jednak gdy przekażesz obiekt wyjątku `ExportFailedException(e.)` to później łatwiej jest określić co poszło nie tak:

> pl.droidevs.books.ExampleUnitTest$ExportFailedException: java.io.FileNotFoundException: filename.txt (No such file or directory)
	at pl.droidevs.books.ExampleUnitTest.test(ExampleUnitTest.java:29)

2018-01-05 11:36 UTC, merged